# Generated by Django 4.2 on 2023-04-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryModel',
        ),
    ]
