# Generated by Django 4.2 on 2023-04-30 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_entrymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('entry_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
